export const GAMES = [
  {
    id: 'cs2',
    name: 'CS2',
    fullName: 'Counter-Strike 2',
    emoji: '🔫',
    color: '#f97316',
    gradient: 'from-orange-600 to-yellow-600',
    accentColor: 'rgba(249, 115, 22, 0.8)',
    tags: ['FPS', 'Tático', 'Competitivo'],
    description: 'FPS tático — encontre seu squad',
  },
  {
    id: 'valorant',
    name: 'Valorant',
    fullName: 'Valorant',
    emoji: '⚡',
    color: '#ff4655',
    gradient: 'from-red-500 to-pink-600',
    accentColor: 'rgba(255, 70, 85, 0.8)',
    tags: ['FPS', 'Agentes', 'Tático'],
    description: 'FPS tático com agentes',
  },
  {
    id: 'lol',
    name: 'LoL',
    fullName: 'League of Legends',
    emoji: '⚔️',
    color: '#c89b3c',
    gradient: 'from-yellow-600 to-amber-700',
    accentColor: 'rgba(200, 155, 60, 0.8)',
    tags: ['MOBA', 'Estratégia', '5v5'],
    description: 'MOBA clássico — monte seu time',
  },
  {
    id: 'fortnite',
    name: 'Fortnite',
    fullName: 'Fortnite',
    emoji: '🏗️',
    color: '#00d4ff',
    gradient: 'from-cyan-500 to-blue-600',
    accentColor: 'rgba(0, 212, 255, 0.8)',
    tags: ['Battle Royale', 'Construção', 'Criativo'],
    description: 'Construa, batalhe e sobreviva',
  },
  {
    id: 'minecraft',
    name: 'Minecraft',
    fullName: 'Minecraft',
    emoji: '⛏️',
    color: '#5c9e31',
    gradient: 'from-green-600 to-emerald-700',
    accentColor: 'rgba(92, 158, 49, 0.8)',
    tags: ['Sobrevivência', 'Criativo', 'Aventura'],
    description: 'Crie seu mundo junto',
  },
  {
    id: 'r6',
    name: 'R6 Siege',
    fullName: 'Rainbow Six Siege',
    emoji: '🛡️',
    color: '#e8b04b',
    gradient: 'from-amber-500 to-orange-600',
    accentColor: 'rgba(232, 176, 75, 0.8)',
    tags: ['FPS', 'Tático', 'Destruição'],
    description: 'Operações táticas de cerco',
  },
  {
    id: 'gtav',
    name: 'GTA V',
    fullName: 'GTA V',
    emoji: '🌆',
    color: '#10b981',
    gradient: 'from-emerald-500 to-teal-600',
    accentColor: 'rgba(16, 185, 129, 0.8)',
    tags: ['Mundo Aberto', 'Ação', 'Assaltos'],
    description: 'Mundo aberto — missões em equipe',
  },
];

export function getGameById(id) {
  return GAMES.find((g) => g.id === id) || null;
}